[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
moroft = "EdFDnVxUbLyqaXCphxH3Wj35WRrDswxiVDVAYfAQK6mC"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/Users/petroyaremenko/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 test/anchor/multisig.test.ts"
