[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
moroft = "B7WAb33d9VguwQQ5em1Zt1Whemv2h8jHupbFYt3YGzwP"

[registry]
url = "https://mainnet.helius-rpc.com/?api-key=f7264107-e02c-4366-9e09-eca2439b8f4d"

[provider]
cluster = "Mainnet"
url = "https://mainnet.helius-rpc.com/?api-key=f7264107-e02c-4366-9e09-eca2439b8f4d"
wallet = "keypair.json"
